
#### alle Aufgaben auflisten
GET http://localhost:5000/api/tasks/all
Content-Type: application/json


#### neue Aufgabe erstellen
POST http://localhost:5000/api/tasks
Content-Type: application/json

{
  "title": "Docker und Flask lernen",
  "description": "Docker und Flask lernen und ein kleines Projekt damit umsetzen",
  "due_date": "2025-05-25T17:00:00",
  "list_id": 1
}


#### Aufgabe löschen
DELETE http://localhost:5000/api/tasks/1
Content-Type: application/json


#### aufgabe bearbeiten
PUT http://localhost:5000/api/tasks/1
Content-Type: application/json

{
  "title": "Kapitel 2 durcharbeiten",
  "description": "Kapitel 2 durcharbeiten und die Übungen lösen und die Lösungen abgeben",
  "due_date": "2025-04-10T15:00:00",
  "is_completed": true
}