#### login user
POST  http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "karimiamirhossein12@gmail.com",
  "password": "Sara.2020"
}

#### get user logged in
GET http://localhost:5000/api/auth/user
Content-Type: application/json


#### get users
GET http://localhost:5000/api/auth/users
Content-Type: application/json

#### request password reset
POST  http://localhost:5000/api/auth/request-reset
Content-Type: application/json

{
  "email": "karimiamirhossein12@gmail.com"
}

#### reset password
POST  http://localhost:5000/api/auth/reset-password
Content-Type: application/json

{
  "email": "karimiamirhossein12@gmail.com",
  "code": "394082",          
  "new_password": "Sara.2020"
}


#### user register 
POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "Ghulam",
  "email": "karimiamirhossein12@gmail.com",
  "password": "Sara.2020"
}

#### logout user
POST  http://localhost:5000/api/auth/logout
Content-Type: application/json

{}


